### ISSUE TITLE
Internal Error When Used in VSCode in Windows 10

### ISSUE THREAD

**Issue by bilalbox** [mulesoft-labs/data-weave-language-server#2]
I realize that this hasn't been tested on Windows so I thought you might find it valuable.

## ISSUE:
When I save a file in DWL format, I get a notification from VSCode that was a problem from Dataweave Language Server

## Step to Reproduce:

1. Install the vscode extension via the extensions menu in vscode
2. Create a new file with a valid DW expression and save it in .dwl format (in this case, ~/Desktop/test.dwl)
3. Wait for the error notification to pop-up in vscode

## SYSTEM INFO:
- Windows 10 Build 19042
- vscode:
  - Version: 1.54.3 (user setup)
  -   Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
  -   Date: 2021-03-15T10:55:45.459Z
  -   Electron: 11.3.0
  -   Chrome: 87.0.4280.141
  -   Node.js: 12.18.3
  -   V8: 8.7.220.31-electron.0
  -   OS: Windows_NT x64 10.0.19042

## ERROR OUTPUT:
```log
[Info  - 5:41:24 PM] [DataWeave] Root URI: null
[Info  - 5:41:24 PM] [DataWeave] Initialization Option: null
[Info  - 5:41:30 PM] Artifact: maven@org.mule.weave:wlang:2.3.1-SNAPSHOT was downloaded successfully.
[Info  - 5:41:31 PM] [DataWeaveWorkspaceService] Changed Configuration: {"data-weave":{"wlangVersion":"2.3.1-SNAPSHOT","languageLevel":"2.3.0","validationLevel":"type","batVersion":"1.0.72"}}
[Error - 5:41:52 PM] Request textDocument/hover failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.util.NoSuchElementException: None.get
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:529)
	at scala.None$.get(Option.scala:527)
	at org.mule.weave.lsp.vfs.ProjectVirtualFile.read(ProjectVirtualFile.scala:20)
	at org.mule.weave.v2.sdk.FileBasedWeaveResource.content(WeaveResource.scala:103)
	at org.mule.weave.v2.sdk.WeaveResource.offsetOf(WeaveResource.scala:23)
	at org.mule.weave.v2.sdk.WeaveResource.offsetOf$(WeaveResource.scala:22)
	at org.mule.weave.v2.sdk.FileBasedWeaveResource.offsetOf(WeaveResource.scala:96)
	at org.mule.weave.v2.WeaveEditorSupport.offsetOf(WeaveEditorSupport.scala:30)
	at org.mule.weave.v2.editor.WeaveDocumentToolingService.offsetOf(WeaveDocumentToolingService.scala:419)
	at org.mule.weave.lsp.services.DataWeaveDocumentService.$anonfun$hover$1(DataWeaveDocumentService.scala:99)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 3 more

[Info  - 5:41:59 PM] [DataWeaveWorkspaceService] Changed Watched File : file:///c%3A/Users/bilal/Desktop/test.dwl - Changed
[Error - 5:42:00 PM] Request textDocument/hover failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.util.NoSuchElementException: None.get
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:529)
	at scala.None$.get(Option.scala:527)
	at org.mule.weave.lsp.vfs.ProjectVirtualFile.read(ProjectVirtualFile.scala:20)
	at org.mule.weave.v2.sdk.FileBasedWeaveResource.content(WeaveResource.scala:103)
	at org.mule.weave.v2.sdk.WeaveResource.offsetOf(WeaveResource.scala:23)
	at org.mule.weave.v2.sdk.WeaveResource.offsetOf$(WeaveResource.scala:22)
	at org.mule.weave.v2.sdk.FileBasedWeaveResource.offsetOf(WeaveResource.scala:96)
	at org.mule.weave.v2.WeaveEditorSupport.offsetOf(WeaveEditorSupport.scala:30)
	at org.mule.weave.v2.editor.WeaveDocumentToolingService.offsetOf(WeaveDocumentToolingService.scala:419)
	at org.mule.weave.lsp.services.DataWeaveDocumentService.$anonfun$hover$1(DataWeaveDocumentService.scala:99)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 3 more

```

Let me know if there's any other useful info I can provide. I love the work that you're doing, and even if it has problems the syntax highlighting is already amazing! 👏🏽

**Comment by afelisatti** [comment]
Hi, @bilalbox. Thanks for reporting this. We are working on Windows validations so this information is very valuable as we start improving our test suites. We'll let you know once we start making progress on this so you can give your scenarios another test.

**Comment by afelisatti** [comment]
Hi, @bilalbox. We are now testing in Windows and released a newer version with many fixes for that environment. Could you try this again? Please make sure to uninstall any prior extensions for DataWeave and replace them with our [latest](https://marketplace.visualstudio.com/items?itemName=MuleSoftInc.dataweave) one.

**Comment by bilalbox** [comment]
Hey @afelisatti . It seems to work much better now! I have tried lots of scripts of varying complexity without issue thus far. Kudos to the DW team! ✋🏽 

vscode info:
Version: 1.66.0 (user setup)
Date: 2022-03-30
Electron: 17.2.0
Chrome: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by afelisatti** [comment]
Glad to hear that, @bilalbox!
