### ISSUE TITLE
Tests stops working after adding "http-module" as a dependency

### ISSUE THREAD

**Issue by estebanwasinger** [mulesoft-labs/data-weave-language-server#38]
How to reproduce:

1.  Create a new project 
2. Go to the `pom.xml` file and add 
```xml
        <dependency>
            <groupId>org.mule.weave</groupId>
            <artifactId>http-module</artifactId>
            <version>0.4.2</version>
            <scope>provided</scope>
        </dependency>
```
3. Create a Unit test for the auto-generated function
4. `mvn clean test`

And as result you are going to get 
```
MyModuleTest
Exception in thread "main" org.mule.weave.v2.parser.phase.CompilationException: Unable to resolve reference of: `parentOf`.

99|     path(parentOf(p), "$(baseNameOf(p))-config.properties")
             ^^^^^^^^
Location:
dw::test::internal::Functions (line: 99, column:10)
        at org.mule.weave.v2.parser.phase.PhaseResult.$anonfun$getResult$1(CompilationPhase.scala:72)
        at scala.Option.getOrElse(Option.scala:189)
        at org.mule.weave.v2.parser.phase.PhaseResult.getResult(CompilationPhase.scala:72)
        at org.mule.weave.v2.runtime.DataWeaveScriptingEngine.compile(DataWeaveScriptingEngine.scala:211)
        at org.mule.weave.v2.runtime.DataWeaveScriptingEngine.compileWith(DataWeaveScriptingEngine.scala:250)
        at org.mule.weave.v2.runtime.DataWeaveScriptingEngine.compile(DataWeaveScriptingEngine.scala:288)
        at org.mule.weave.v2.module.test.runner.TestCustomRunner.$anonfun$runTests$4(TestCustomRunner.scala:276)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at org.mule.weave.v2.module.test.runner.TestCustomRunner.runTests(TestCustomRunner.scala:272)
        at org.mule.weave.v2.module.test.runner.TestCustomRunner.run(TestCustomRunner.scala:187)
        at org.mule.weave.v2.module.test.runner.TestRunner$.main(TestRunner.scala:13)
        at org.mule.weave.v2.module.test.runner.TestRunner$.delayedEndpoint$org$mule$weave$v2$module$test$runner$TestRunner$1(TestRunner.scala:7)
        at org.mule.weave.v2.module.test.runner.TestRunner$delayedInit$body.apply(TestRunner.scala:5)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1$adapted(App.scala:80)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at org.mule.weave.v2.module.test.runner.TestRunner$.main(TestRunner.scala:5)
        at org.mule.weave.v2.module.test.runner.TestRunner.main(TestRunner.scala)
```

**Comment by uip-robot-zz** [comment]
Git2Gus App is installed but the `.git2gus/config.json` doesn't exist.

**Comment by machaval** [comment]
Can you try with 0.6.1 That is the latest version.

**Comment by estebanwasinger** [comment]
Thanks, the issue gets fixed!
but now trying to use the library it self like: `fun helloWorld() = log(GET('https://slack.com/api/chat.postMessage'))` it fails with the following:
```
 WeaveRuntimeException:org.mule.weave.v2.parser.exception.WeaveRuntimeException HttpClientService was not registered
org.mule.weave.v2.parser.exception.WeaveRuntimeException: HttpClientService was not registered
        at org.mule.weave.v2.module.http.functions.HttpRequestFunction.$anonfun$doExecute$9(HttpRequestFunction.scala:115)
        at scala.Option.getOrElse(Option.scala:189)
        at org.mule.weave.v2.module.http.functions.HttpRequestFunction.doExecute(HttpRequestFunction.scala:115)
        at org.mule.weave.v2.core.functions.BaseTernaryFunctionValue.call(TernaryFunctionValue.scala:30)
        at org.mule.weave.v2.core.functions.BaseTernaryFunctionValue.call$(TernaryFunctionValue.scala:29)
        at org.mule.weave.v2.module.http.functions.HttpRequestFunction.call(HttpRequestFunction.scala:47)
        at org.mule.weave.v2.core.functions.TernaryInterceptedFunctionValue.$anonfun$doExecute$4(InterceptedFunctionValue.scala:249)
        at org.mule.weave.v2.core.functions.InterceptedFunctionCallBack.doExecute(InterceptedFunctionValue.scala:274)
        at org.mule.weave.v2.core.functions.BaseUnaryFunctionValue.call(UnaryFunctionValue.scala:40)
        at org.mule.weave.v2.core.functions.BaseUnaryFunctionValue.call$(UnaryFunctionValue.scala:39)
        at org.mule.weave.v2.core.functions.InterceptedFunctionCallBack.call(InterceptedFunctionValue.scala:270)
        at org.mule.weave.v2.model.service.SecurityManagerCheckFunctionValue$.$anonfun$doExecute$2(SecurityManagerService.scala:106)
        at org.mule.weave.v2.model.service.NoSecurityManagerService$.executeWith(SecurityManagerService.scala:69)
        at org.mule.weave.v2.model.service.SecurityManagerCheckFunctionValue$.doExecute(SecurityManagerService.scala:106)
        at org.mule.weave.v2.model.service.SecurityManagerCheckFunctionValue$.doExecute(SecurityManagerService.scala:100)
        at org.mule.weave.v2.core.functions.BaseQuternaryFunctionValue.call(QuaternaryFunctionValue.scala:42)
        at org.mule.weave.v2.core.functions.BaseQuternaryFunctionValue.call$(QuaternaryFunctionValue.scala:41)
        at org.mule.weave.v2.model.service.SecurityManagerCheckFunctionValue$.call(SecurityManagerService.scala:100)
        at org.mule.weave.v2.core.functions.TernaryInterceptedFunctionValue.doExecute(InterceptedFunctionValue.scala:248)
        at org.mule.weave.v2.core.functions.BaseTernaryFunctionValue.call(TernaryFunctionValue.scala:30)
        at org.mule.weave.v2.core.functions.BaseTernaryFunctionValue.call$(TernaryFunctionValue.scala:29)
        at org.mule.weave.v2.core.functions.TernaryInterceptedFunctionValue.call(InterceptedFunctionValue.scala:229)
        at org.mule.weave.v2.interpreted.node.executors.TernaryFunctionExecutor.doCall(TernaryFunctionExecutor.scala:129)
        at org.mule.weave.v2.interpreted.node.executors.TernaryFunctionExecutor.executeTernary(TernaryFunctionExecutor.scala:104)
        at org.mule.weave.v2.interpreted.node.TernaryFunctionCallNode.doExecute(FunctionCallNode.scala:102)
        at org.mule.weave.v2.interpreted.node.ValueNode.execute(ValueNode.scala:26)
        at org.mule.weave.v2.interpreted.node.ValueNode.execute$(ValueNode.scala:21)
        at org.mule.weave.v2.interpreted.node.TernaryFunctionCallNode.execute(FunctionCallNode.scala:95)
        at org.mule.weave.v2.interpreted.node.structure.function.BinaryFunctionExecutionContextAwareFunction.$anonfun$doExecute$3(ExecutionContextAwareFunctionValue.scala:309)
        at org.mule.weave.v2.interpreted.ExecutionContext.runInFrame(ExecutionContext.scala:168)
        at org.mule.weave.v2.interpreted.ExecutionContext.runInFrame$(ExecutionContext.scala:162)
        at org.mule.weave.v2.interpreted.DefaultExecutionContext.runInFrame(ExecutionContext.scala:365)
        at org.mule.weave.v2.interpreted.node.structure.function.BinaryFunctionExecutionContextAwareFunction.doExecute(ExecutionContextAwareFunctionValue.scala:309)
        at org.mule.weave.v2.core.functions.BaseBinaryFunctionValue.doCall(BinaryFunctionValue.scala:43)
        at org.mule.weave.v2.core.functions.BaseBinaryFunctionValue.doCall$(BinaryFunctionValue.scala:42)
        at org.mule.weave.v2.interpreted.node.structure.function.BinaryFunctionExecutionContextAwareFunction.doCall(ExecutionContextAwareFunctionValue.scala:257)
        at org.mule.weave.v2.model.values.BaseFunctionValue.call(FunctionValue.scala:153)
        at org.mule.weave.v2.model.values.BaseFunctionValue.call$(FunctionValue.scala:146)
        at org.mule.weave.v2.interpreted.node.structure.function.BinaryFunctionExecutionContextAwareFunction.call(ExecutionContextAwareFunctionValue.scala:257)
        at org.mule.weave.v2.interpreted.node.executors.DefaultFunctionCallExecutor.doCall(DefaultFunctionCallExecutor.scala:87)
        at org.mule.weave.v2.interpreted.node.executors.DefaultFunctionCallExecutor.execute(DefaultFunctionCallExecutor.scala:69)
        at org.mule.weave.v2.interpreted.node.DefaultFunctionCallNode.doExecute(FunctionCallNode.scala:27)
        at org.mule.weave.v2.interpreted.node.ValueNode.execute(ValueNode.scala:26)
        at org.mule.weave.v2.interpreted.node.ValueNode.execute$(ValueNode.scala:21)
        at org.mule.weave.v2.interpreted.node.DefaultFunctionCallNode.execute(FunctionCallNode.scala:23)
        at org.mule.weave.v2.interpreted.node.DefaultFunctionCallNode.executeArgs(FunctionCallNode.scala:34)
        at org.mule.weave.v2.interpreted.node.DefaultFunctionCallNode.doExecute(FunctionCallNode.scala:26)
        at org.mule.weave.v2.interpreted.node.ValueNode.execute(ValueNode.scala:26)
        at org.mule.weave.v2.interpreted.node.ValueNode.execute$(ValueNode.scala:21)
        at org.mule.weave.v2.interpreted.node.DefaultFunctionCallNode.execute(FunctionCallNode.scala:23)
        at org.mule.weave.v2.interpreted.node.ValueNode.execute$(ValueNode.scala:21)
        at org.mule.weave.v2.interpreted.node.structure.DocumentNode.execute(DocumentNode.scala:11)
        at org.mule.weave.v2.interpreted.InterpretedMappingExecutableWeave.execute(InterpreterMappingCompilerPhase.scala:196)
        at org.mule.weave.v2.runtime.DataWeaveScript.doExec(DataWeaveScriptingEngine.scala:770)
        at org.mule.weave.v2.runtime.DataWeaveScript.exec(DataWeaveScriptingEngine.scala:728)
        at org.mule.weave.v2.module.test.runner.TestCustomRunner.runTheTest(TestCustomRunner.scala:354)
        at org.mule.weave.v2.module.test.runner.TestCustomRunner.runTest(TestCustomRunner.scala:339)
        at org.mule.weave.v2.module.test.runner.TestCustomRunner.$anonfun$runTests$4(TestCustomRunner.scala:277)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at org.mule.weave.v2.module.test.runner.TestCustomRunner.runTests(TestCustomRunner.scala:272)
        at org.mule.weave.v2.module.test.runner.TestCustomRunner.run(TestCustomRunner.scala:187)
        at org.mule.weave.v2.module.test.runner.TestRunner$.main(TestRunner.scala:13)
        at org.mule.weave.v2.module.test.runner.TestRunner$.delayedEndpoint$org$mule$weave$v2$module$test$runner$TestRunner$1(TestRunner.scala:7)
        at org.mule.weave.v2.module.test.runner.TestRunner$delayedInit$body.apply(TestRunner.scala:5)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1$adapted(App.scala:80)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at org.mule.weave.v2.module.test.runner.TestRunner$.main(TestRunner.scala:5)
        at org.mule.weave.v2.module.test.runner.TestRunner.main(TestRunner.scala)
```

**Comment by machaval** [comment]
You are missing an http implemetation module such http-netty-module
